name: Coverage Report
on: [push]
jobs:
    coverage:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: ['1.14']
        name: Go ${{ matrix.go }} sample
        steps:
            - uses: actions/checkout@v2
            - name: Setup go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go }}

            - run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
            - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r coverage.txt -t ${{ secrets.CODACY_PROJECT_TOKEN }}
