name: Test
on: [push]
jobs:
    coverage:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: ['1.14']
        name: Go ${{ matrix.go }} sample
        steps:
            - uses: actions/checkout@v2
            - name: Setup go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go }}
            - uses: actions/checkout@v2
            - name: Run codacy-coverage-reporter
              uses: codacy/codacy-coverage-reporter-action@v1
              with:
                  project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                  coverage-reports: cobertura.xml
