name: Test
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: ['1.14', '1.13']
        name: Go ${{ matrix.go }} sample
        steps:
            - uses: actions/checkout@v2
            - name: Setup go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go }}
              if: matrix.os == 'ubuntu-latest'
            - run: sudo apt update && sudo apt install -y --no-install-recommends libsdl2{,-image,-mixer,-ttf,-gfx}-dev
            - run: go test ./...
